### ISSUE TITLE
Format configuration as no effect

### ISSUE THREAD

**Issue by kawas44** [Deraen/vim-cider#3]
Hi,

For information I tried to configure the clean-ns prefix-rewriting option, but it does nothing with either true or false, on vim or nvim, on ubuntu or osx.

Option: `let g:refactor_nrepl_options = '{:prefix-rewriting false}'`

Editors:
`NVIM 0.1.7`
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35)
Rustines incluses : 1-95`

Lein: `Leiningen 2.7.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM`

Lein plugins:
```clojure
[org.clojure/tools.nrepl "0.2.13" :exclusions [org.clojure/clojure]]
[cider/cider-nrepl "0.15.1"]
[refactor-nrepl "2.3.1"]
```

Cheers

**Comment by Deraen** [comment]
Should fixed by #5, just tested the configuration and it works now.
